import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { Inter } from 'next/font/google'
import "./globals.css";
import Header from "../components/Header";
import { SessionProvider } from "next-auth/react";
import { auth } from "../../auth";

// const lato = Lato({ weight: ['100', '300', '400', '700', '900'], subsets: ["latin"] });
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Health Learning",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  const session = await auth();

  return (
    <html lang="pt-br">
      <SessionProvider session={session}>
        <body className={inter.className}>
           <main className="h-screen text-gray-main flex flex-col">
            <Header/>
            <section className="px-4 md:px-20 pt-6 md:pt-10 pb-6 md:pb-10">
              {children}
            </section>
          </main>
        </body>
      </SessionProvider>
    </html>
  );
}
