services:
  backend-fastapi:
    build: .
    container_name: backend-fastapi
    ports:
      - '4000:4000'
    environment:
      PORT: 4000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    